### PR TITLE
feat: :wrench: Added devcontainer file. Needs to be tested first!

### LINKED ISSUE #32: Easier team development with Dev containers
Both VSCode and Pycharm allow the use of Dev containers, which are docker environments built in a way that allows us to develop inside of them. Using these would solve the problem of having each person install all the necessary software etc, and instead run the Dev container that will install and build everything itself. Plus, it will standard the operating system we would develop on (fewer "it works on my computer" issues).

### PR DESCRIPTION
**Pull request by lwjohnst86**
I haven't fully been able to test it, since I think I have issues with my Docker install. But I think it should work. Can any of you test it out by pulling this branch, opening the project in VS Code and selecting the pop-up that says "open in Dev Container". Then after it builds and starts up, go to the Terminal and type out "just build-website".

Closes #32

### CODE REVIEW

**Comment by K-Beicher** [comment]
Tried to, I'm sure I'm just missing a step here, what do I need to run in order to get the pop-up?

**Comment by lwjohnst86** [comment]
ah you're right, I forgot to add the vscode extension to the vscode folder. I'll fix that than push it up

**Comment by lwjohnst86** [comment]
I added it. The other thing I forgot to mention is that to open the Dev Container, you also need open Docker, so it is running in the background.

**Comment by K-Beicher** [comment]
Tested and works fine here

**Review by K-Beicher — APPROVED** [review]

**Comment by signekb** [comment]
I'm not getting the pop-up to open in a dev container. I have Docker Desktop open (and have switched to the feat/devcontainer branch ofc). What am I missing?

**Comment by lwjohnst86** [comment]
Have you installed the recommended extensions? Otherwise, try using the command palette and typing "reopen in dev container".

**Comment by signekb** [comment]
AH, I found the little notification with @K-Beicher 's help. Not exactly screaming for attention 😛

**Comment by signekb** [comment]
Do we want the vs extensions we use to come installed in the dev container? Or do we want to keep that separate? 
Screenshot 2023-12-04 at 09 47 14

**Comment by lwjohnst86** [comment]
@signekb hmmm, I think because we have the recommended extensions already in the `settings.json` file, it will install them after you've opened the devcontainer and selected "yes" to installing the recommended extensions. There might be a way to install it automatically though. The tricky part is the devcontainers aren't just a vscode thing, but also available in PyCharm. Which doesn't have extensions.

**Comment by signekb** [comment]
@lwjohnst86 Ah, yeah, very good point. I think you're right - let's keep the extensions in the `.vscode/settings.json`

**Review by signekb — APPROVED** [review]
Works for me too 👍

**Pull request merged**
